- name: copy planningpoker repo
  synchronize:
      compress: yes
      group: no
      checksum: yes
      copy_links: yes
      links: yes
      partial: yes
      perms: yes
      recursive: yes
      times: yes
      delete: yes
      src: "{{ playbook_dir }}/.."
      dest: /home/ec2-user/planningpoker
      rsync_opts:
      # don't upload deps for Ansible and npm
      - "--exclude=venv"
      - "--exclude=node_modules"
      - "--exclude=.git"

